# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalNVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=64)),
                ('ack', models.CharField(blank=True, max_length=32)),
                ('profilestatus', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('profileid', models.CharField(blank=True, max_length=32)),
                ('profilereference', models.CharField(blank=True, max_length=128)),
                ('correlationid', models.CharField(blank=True, max_length=32)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('payerid', models.CharField(blank=True, max_length=64)),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name=b'First Name')),
                ('lastname', models.CharField(blank=True, max_length=255, verbose_name=b'Last Name')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name=b'Street Address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name=b'City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name=b'State')),
                ('countrycode', models.CharField(blank=True, max_length=2, verbose_name=b'Country')),
                ('zip', models.CharField(blank=True, max_length=32, verbose_name=b'Postal / Zip Code')),
                ('invnum', models.CharField(blank=True, max_length=255)),
                ('custom', models.CharField(blank=True, max_length=255)),
                ('flag', models.BooleanField(default=False)),
                ('flag_code', models.CharField(blank=True, max_length=32)),
                ('flag_info', models.TextField(blank=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('query', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paypal_nvp',
                'verbose_name': 'PayPal NVP',
            },
        ),
    ]
